### ISSUE TITLE
Race conditions in Jenkins pipeline with parallel mstest execution 

### ISSUE THREAD

**Issue by SafuanA** [jenkinsci/mstest-plugin#29]
We rely on running unittests in parallel to improve performance. Recently, we extended our unittests, and since then, we have encountered this error.

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.462
OS: Windows Server 2019 - 10.0
Java: 17.0.11 - Azul Systems, Inc. (OpenJDK 64-Bit Server VM)
---
mstest:1.0.5
  ```

</details>

# Setup
1. Configure the Jenkinsfile to run different mstest calls in [parallel](https://www.jenkins.io/doc/book/pipeline/syntax/).
2. Run the pipeline that uses the mstest plugin in parallel.

Example Jenkins configuration:
```
stage('Quality Check') {
    parallel {
		// this stage is executed in parallel with 'Unit Tests 2'
        stage('Unit Tests 1') {
			steps { 
				RunUnitTest1()
				// mstest plugin call for Unit Test 1 results
				mstest testResultsFile: "**/UnitTest1/*.trx"
			}
        }
		// this stage is executed in parallel with 'Unit Tests 1'
        stage('Unit Tests 2') {
			steps { 
				RunUnitTest2()
				// mstest plugin call for Unit Test 2 results
				mstest testResultsFile: "**/UnitTest2/*.trx"
			}
        }
    }
}
```

# Expected results
Each time a successful run through the pipeline with completion of all phases.

# Actual results
Due to a race condition, the run may fail in some cases with one of the following errors.

## Pipeline may fail with either this error
```
jenkins.util.io.CompositeIOException: Unable to delete '<path>\workspace\temporary-junit-reports'. Tried 3 times (of a maximum of 3) waiting 0.1 Sekunden between attempts.
```

This error suggests a potential race condition related to the "temporary-junit-reports" directory and "temp-junit.xml". Possible scenarios include:

+ The directory cannot be deleted because a file in this directory is used by another stage.

## Occasionally the pipeline may fail with this error instead of the previous one
```
java.io.IOException: [MSTEST-PLUGIN] Unable to transform the MSTest report. Please report this issue to the plugin author
hudson.remoting.ProxyException: org.xml.sax.SAXParseException; systemId: file:[...]/workspace/temporary-junit-reports/temp-junit.xml; lineNumber: 17; columnNumber: 1; Content is not allowed in prolog.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
	at PluginClassLoader for mstest//hudson.plugins.mstest.MSTestReportConverter.splitJUnitFile(MSTestReportConverter.java:178)
	at PluginClassLoader for mstest//hudson.plugins.mstest.MSTestReportConverter.transform(MSTestReportConverter.java:152)
	at PluginClassLoader for mstest//hudson.plugins.mstest.MSTestReportConverter.transform(MSTestReportConverter.java:70)
	at PluginClassLoader for mstest//hudson.plugins.mstest.MSTestTransformer.invoke(MSTestTransformer.java:72)
Also:   hudson.remoting.ProxyException: org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: a044cb9f-96d6-4468-9f48-5437cffdeabf
Caused: hudson.remoting.ProxyException: java.io.IOException: [MSTEST-PLUGIN] Unable to transform the MSTest report. Please report this issue to the plugin author
	at PluginClassLoader for mstest//hudson.plugins.mstest.MSTestTransformer.invoke(MSTestTransformer.java:75)
	at PluginClassLoader for mstest//hudson.plugins.mstest.MSTestTransformer.invoke(MSTestTransformer.java:22)
	at hudson.FilePath.act(FilePath.java:1235)
	at hudson.FilePath.act(FilePath.java:1218)
	at PluginClassLoader for mstest//hudson.plugins.mstest.MSTestPublisher.perform(MSTestPublisher.java:148)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

+ Stage one reads the partially written file of stage two, which is still writing.

# Additional context

**Specifically, the following parts of the code may be contributing to the issue:**

***this part in MSTestPublisher.java***

```
recordTestResult(MSTestTransformer.JUNIT_REPORTS_PATH + "/TEST-*.xml", build, workspace, listener);
workspace.child(MSTestTransformer.JUNIT_REPORTS_PATH).deleteRecursive();
```

***and this part in MSTestReportConverter.java***

```
File junitOutputPath = new File(ws, JUNIT_REPORTS_PATH);
```

***and this part in MSTestReportConverter.java***

```
File junitTargetFile = new File(junitOutputPath, TEMP_JUNIT_FILE_STR);
```

# Proposed solution
Consider using unique directories for JUnit report paths to avoid race conditions.

**Pull request**
To create unique directories we append a uuid to the directory name. Including the separating dash, this adds 37 characters to the path length. In rare cases, this can lead to a length that exceeds the maximum path length of the system. Under Windows, this limit is still 260 characters by default. In our case, the path length was 94 characters and with the new solution 131 characters, which leaves plenty of room for more characters on other systems. To mitigate this problem slightly, we have changed "temporary-junit-reports" to "temp-junit-reports", as we are convinced that this has no disadvantages and saves 5 characters
However, if a solution with the same length is desired, there are several ways to achieve this, which we will not go into here.

We appreciate your attention to this issue as it significantly impacts our CI/CD pipeline. Please let us know if you need any additional information.

**Comment by MichaelNel** [comment]
We appear to be hitting the same issue. Would be good to see that PR merged! @SafuanA Did you find a workaround in the meantime?

**Comment by ueli-werner** [comment]
@MichaelNel We simply create the plugin with the PR and copy it into the plugin directory.
